FROM python:3-bookworm AS docs

WORKDIR /app
COPY Makefile requirements.txt ./
RUN make docs-deps

COPY ./mkdocs.yml ./
COPY ./docs ./docs
RUN make docs-build


FROM node:18-bookworm AS web

WORKDIR /app
COPY Makefile .
COPY ./web/package.json ./web/package-lock.json ./web/
RUN make web-deps

COPY ./web ./web
RUN make web-build


FROM golang:1.25-bookworm AS builder
ARG VERSION=dev
ARG COMMIT=unknown

# cli & server
WORKDIR /app
COPY Makefile .
COPY go.mod go.sum main.go ./
COPY ./client ./client
COPY ./cmd ./cmd
COPY ./db ./db
COPY ./log ./log
COPY ./message ./message
COPY ./model ./model
COPY ./payments ./payments
COPY ./server ./server
COPY ./user ./user
COPY ./util ./util
COPY ./webpush ./webpush

COPY --from=docs /app/server/docs ./server/docs
COPY --from=web /app/server/site ./server/site
RUN make VERSION=$VERSION COMMIT=$COMMIT cli-linux-server


FROM golang:1.25-bookworm AS tzdata

RUN DEBIAN_FRONTEND=noninteractive \
  apt install --yes --no-install-recommends tzdata


FROM gcr.io/distroless/base-debian12
ARG VERSION=dev

LABEL org.opencontainers.image.authors="philipp.heckel@gmail.com"
LABEL org.opencontainers.image.url="https://ntfy.sh/"
LABEL org.opencontainers.image.documentation="https://docs.ntfy.sh/"
LABEL org.opencontainers.image.source="https://github.com/binwiederhier/ntfy"
LABEL org.opencontainers.image.vendor="Philipp C. Heckel"
LABEL org.opencontainers.image.licenses="Apache-2.0, GPL-2.0"
LABEL org.opencontainers.image.title="ntfy"
LABEL org.opencontainers.image.description="Send push notifications to your phone or desktop using PUT/POST"
LABEL org.opencontainers.image.version="$VERSION"

COPY --from=tzdata /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /app/dist/ntfy_linux_server/ntfy /usr/bin/ntfy

EXPOSE 80/tcp
ENTRYPOINT ["ntfy"]
